apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres-configmap
data:
  POSTGRES_DB_HOST: postgres
  #base de Simulate
  POSTGRES_DB_Simulate: simulate
  #base de Register
  POSTGRES_DB_Register: register
  #base de Request
  POSTGRES_DB_Request: request