server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/api/v1/simulate/**
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/api/v1/users/**
        - id: requestCredit-service
          uri: lb://requestCredit-service
          predicates:
            - Path=/api/v1/loan_requests/**, /api/v1/documents/**
        - id: evaluateCredit-service
          uri: lb://evaluateCredit-service
          predicates:
            - Path=/api/v1/loanEvaluation/**, /api/v1/documents/**
        - id: followCredit-service
          uri: lb://followCredit-service
          predicates:
            - Path=/api/v1/loanTracking/**
